name: chatgpt_audio_learn
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  audioplayers: ^5.2.0
  path_provider: ^2.0.14
  provider: ^6.0.5
  youtube_explode_dart: ^2.0.2
  just_audio: ^0.9.31
  http: ^1.1.0
  googleapis: ^11.2.0
  googleapis_auth: ^1.4.0
  on_audio_query: ^2.6.2
  audio_video_progress_bar: ^2.0.1
  rxdart: ^0.27.7
  url_launcher: ^6.1.10
  another_flushbar: ^1.12.29
  workmanager: ^0.5.1
  curved_navigation_bar: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  intl_utils: ^2.0.0
  mockito: ^5.3.2
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/audio/
    - assets/images/

